=== Deltares/HYDROLIB/contrib/Arcadis/scripts/exampledata/Zwolle-Minimodel/1D2D-DIMR/rtc/rtcDataConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<schema xmlns:rtc="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="rtcSharedTypes.xsd"/>
	<element name="rtcDataConfig" type="rtc:RTCDataConfigComplexType"/>
	<complexType name="RTCDataConfigComplexType">
		<sequence>
			<element name="importSeries" type="rtc:RTCSeriesImportComplexType">
				<annotation>
					<documentation>Import time series RTC-Tools imports from XML files or other interfaces</documentation>
				</annotation>
			</element>
			<element name="exportSeries" type="rtc:RTCSeriesExportComplexType">
				<annotation>
					<documentation>Export time series RTC-Tools genenerates and exports to XML or csv files or supplies to other applications via other interfaces</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="RTCSeriesImportComplexType">
		<sequence>
			<element name="PITimeSeriesFile" type="rtc:PITimeSeriesImportFileComplexType" minOccurs="0"/>
			<element name="timeSeries" type="rtc:RTCTimeSeriesComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Time series for importing and exporting optionally including the mapping from to Delft-FEWS or OpenMI </documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="RTCSeriesExportComplexType">
		<sequence>
			<element name="CSVTimeSeriesFile" type="rtc:CSVTimeSeriesFileComplexType" minOccurs="0">
				<annotation>
					<documentation>Comma-separated file for data exports. Note that this option is only used in the exportSeries element. If selected, all available time series will be exported.</documentation>
				</annotation>
			</element>
			<element name="PITimeSeriesFile" type="rtc:PITimeSeriesExportFileComplexType" minOccurs="0"/>
			<element name="timeSeries" type="rtc:RTCTimeSeriesComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Time series for importing and exporting optionally including the mapping from to Delft-FEWS or OpenMI </documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="RTCTimeSeriesComplexType">
		<annotation>
			<documentation>The header is used to specify the link to the location
                and the contents</documentation>
		</annotation>
		<sequence>
			<element name="PITimeSeries" type="rtc:PITimeSeriesComplexType" minOccurs="0">
				<annotation>
					<documentation>Time series definition of the PI XML time series format of Delft-FEWS</documentation>
				</annotation>
			</element>
			<element name="OpenMIExchangeItem" type="rtc:OpenMIExchangeItemComplexType" minOccurs="0">
				<annotation>
					<documentation>Time series definition of the OpenMI format for the online coupling of models during runtime</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" use="required">
			<annotation>
				<documentation>ID of time series in RTC Tools configuration.</documentation>
			</annotation>
			<simpleType>
				<restriction base="rtc:TimeSeriesSimpleType"/>
			</simpleType>
		</attribute>
		<attribute name="vectorLength" use="optional">
			<annotation>
				<documentation>Optional vector length for vector definition. This attribute generates ids according to id[0], id[1], ..., id[length-1] according to the configured id above.</documentation>
			</annotation>
			<simpleType>
				<restriction base="int">
					<minInclusive value="1"/>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="validation" use="optional">
			<annotation>
				<documentation>data valadidation to make sure that the state or the complete time series is available after startup of the application</documentation>
			</annotation>
			<simpleType>
				<restriction base="string">
					<enumeration value="NO"/>
					<enumeration value="STATE"/>
					<enumeration value="UPDATE"/>
					<enumeration value="UPDATE_EXCEPT_STATE"/>
					<enumeration value="FORECAST"/>
					<enumeration value="FORECAST_EXCEPT_T0"/>
					<enumeration value="ALL"/>
					<enumeration value="ALL_EXCEPT_STATE"/>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>
	<complexType name="PITimeSeriesComplexType">
		<annotation>
			<documentation>The header is used to specify the link to the location
                and the contents</documentation>
		</annotation>
		<sequence>
			<element name="locationId" type="string">
				<annotation>
					<documentation>Location ID in Delft-FEWS PI-XML file</documentation>
				</annotation>
			</element>
			<element name="parameterId" type="string">
				<annotation>
					<documentation>Parameter ID in Delft-FEWS PI-XML file</documentation>
				</annotation>
			</element>
			<element name="qualifierId" type="string" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional qualifier ID in Delft-FEWS PI-XML file</documentation>
				</annotation>
			</element>
			<element name="timeStep" type="rtc:TimeStepComplexType" minOccurs="0">
				<annotation>
					<documentation>Equidistant time step of time series with optional multiplier of divider</documentation>
				</annotation>
			</element>
			<element name="unit" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional check for this unit during import, write this unit optionally when export the time series</documentation>
				</annotation>
			</element>
			<element name="interpolationOption" type="rtc:PIInterpolationOptionEnumStringType" minOccurs="0">
				<annotation>
					<documentation>Interpolation option in data import</documentation>
				</annotation>
			</element>
			<element name="extrapolationOption" type="rtc:PIExtrapolationOptionEnumStringType" minOccurs="0">
				<annotation>
					<documentation>Extrapolation option in data import</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="PIInterpolationOptionEnumStringType">
		<restriction base="string">
			<enumeration value="BLOCK"/>
			<enumeration value="LINEAR"/>
		</restriction>
	</simpleType>
	<simpleType name="PIExtrapolationOptionEnumStringType">
		<restriction base="string">
			<enumeration value="BLOCK"/>
			<enumeration value="PERIODIC"/>
		</restriction>
	</simpleType>
	<complexType name="OpenMIExchangeItemComplexType">
		<sequence>
			<element name="elementId" type="string">
				<annotation>
					<documentation>OpenMI element ID, corresponds to the locationId</documentation>
				</annotation>
			</element>
			<element name="quantityId" type="string">
				<annotation>
					<documentation>OpenMI quantity ID, corresponds to the parameterId</documentation>
				</annotation>
			</element>
			<element name="unit" type="rtc:UnitEnumStringType">
				<annotation>
					<documentation>Selection of supported units</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<simpleType name="UnitEnumStringType">
		<restriction base="string">
			<enumeration value="m"/>
			<enumeration value="m^2"/>
			<enumeration value="m^3"/>
			<enumeration value="m^3/s"/>
			<enumeration value="s"/>
		</restriction>
	</simpleType>
	<complexType name="PITimeSeriesImportFileComplexType">
		<sequence>
			<element name="timeSeriesFile" type="string">
				<annotation>
					<documentation>Name of the file containing timeseries data. </documentation>
				</annotation>
			</element>
			<element name="useBinFile" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>OBSOLETE. Still here for backwards compatibility. Remove after next release.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="PITimeSeriesExportFileComplexType">
		<sequence>
			<element name="timeSeriesFile" type="string">
				<annotation>
					<documentation>Name of the file containing timeseries data. </documentation>
				</annotation>
			</element>
			<element name="useBinFile" type="boolean" default="false" minOccurs="0">
				<annotation>
					<documentation>When true the events in the PI time series file are read from / written into a binairy file instead of the xml file.
The xml file only contains the time series headers and optionally a time zone.
The binairy file has the same name as the xml file only the extension is "bin" instead of "xml". The byte order in the bin file is always Intel x86.
                </documentation>
				</annotation>
			</element>
			<element name="adjointOutput" type="boolean" default="false" minOccurs="0"/>
		</sequence>
	</complexType>
	<complexType name="CSVTimeSeriesFileComplexType">
		<attribute name="decimalSeparator" type="rtc:SeparatorEnumStringType" use="optional" default="."/>
		<attribute name="delimiter" type="rtc:SeparatorEnumStringType" use="optional" default=","/>
		<attribute name="adjointOutput" type="boolean" use="optional" default="false"/>
	</complexType>
	<simpleType name="SeparatorEnumStringType">
		<restriction base="string">
			<enumeration value="."/>
			<enumeration value=","/>
			<enumeration value=";"/>
		</restriction>
	</simpleType>
</schema>

=== Deltares/HYDROLIB/hydrolib/tests/data/complex_controllers_2/rtcDataConfig.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rtcDataConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:rtc="http://www.wldelft.nl/fews" xmlns="http://www.wldelft.nl/fews" xsi:schemaLocation="http://www.wldelft.nl/fews D:\4390.10\HYDROLIB\hydrolib\tests\New%20folder\New%20folder%20(2)\rtc\rtcDataConfig.xsd">
  <importSeries>
    <PITimeSeriesFile>
      <timeSeriesFile>timeseries_import.xml</timeSeriesFile>
      <useBinFile>false</useBinFile>
    </PITimeSeriesFile>
    <timeSeries id="[Input]ObsS_96789/Water level (op)">
      <OpenMIExchangeItem>
        <elementId>ObsS_96789</elementId>
        <quantityId>Water level (op)</quantityId>
        <unit>m</unit>
      </OpenMIExchangeItem>
    </timeSeries>
  </importSeries>
  <exportSeries>
    <CSVTimeSeriesFile decimalSeparator="." delimiter="," adjointOutput="false"></CSVTimeSeriesFile>
    <PITimeSeriesFile>
      <timeSeriesFile>timeseries_export.xml</timeSeriesFile>
      <useBinFile>false</useBinFile>
    </PITimeSeriesFile>
    <timeSeries id="[Output]S_96789/Crest level (s)">
      <OpenMIExchangeItem>
        <elementId>S_96789</elementId>
        <quantityId>Crest level (s)</quantityId>
        <unit>m</unit>
      </OpenMIExchangeItem>
    </timeSeries>
  <timeSeries id="[IP]Control group S_96789/PID Rule" /> 
  <timeSeries id="[DP]Control group S_96789/PID Rule" /> 
  </exportSeries>
</rtcDataConfig>

=== Deltares/HYDROLIB/hydrolib/tests/data/complex_controllers/rtcDataConfig.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rtcDataConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:rtc="http://www.wldelft.nl/fews" xmlns="http://www.wldelft.nl/fews" xsi:schemaLocation="http://www.wldelft.nl/fews D:\4390.10\HYDROLIB\hydrolib\tests\New%20folder\New%20folder%20(2)\rtc\rtcDataConfig.xsd">
  <importSeries>
    <PITimeSeriesFile>
      <timeSeriesFile>timeseries_import.xml</timeSeriesFile>
      <useBinFile>false</useBinFile>
    </PITimeSeriesFile>
    <timeSeries id="[Input]ObsS_96684_1/Water level (op)">
      <OpenMIExchangeItem>
        <elementId>ObsS_96684_1</elementId>
        <quantityId>Water level (op)</quantityId>
        <unit>m</unit>
      </OpenMIExchangeItem>
    </timeSeries>
    <timeSeries id="Control Group 1/Time Rule True">
      <PITimeSeries>
        <locationId>[TimeRule]Control Group 1/Time Rule True</locationId>
        <parameterId>TimeSeries</parameterId>
        <interpolationOption>LINEAR</interpolationOption>
        <extrapolationOption>BLOCK</extrapolationOption>
      </PITimeSeries>
    </timeSeries>
    <timeSeries id="Control Group 1/Time rule False">
      <PITimeSeries>
        <locationId>[TimeRule]Control Group 1/Time rule False</locationId>
        <parameterId>TimeSeries</parameterId>
        <interpolationOption>LINEAR</interpolationOption>
        <extrapolationOption>BLOCK</extrapolationOption>
      </PITimeSeries>
    </timeSeries>
  </importSeries>
  <exportSeries>
    <CSVTimeSeriesFile decimalSeparator="." delimiter="," adjointOutput="false"></CSVTimeSeriesFile>
    <PITimeSeriesFile>
      <timeSeriesFile>timeseries_export.xml</timeSeriesFile>
      <useBinFile>false</useBinFile>
    </PITimeSeriesFile>
    <timeSeries id="[Output]S_96684/Crest level (s)">
      <OpenMIExchangeItem>
        <elementId>S_96684</elementId>
        <quantityId>Crest level (s)</quantityId>
        <unit>m</unit>
      </OpenMIExchangeItem>
    </timeSeries>
    <timeSeries id="[Status]Control Group 1/Standard Condition" />
  </exportSeries>
</rtcDataConfig>

=== Deltares/HYDROLIB/hydrolib/tests/data/complex_controllers_4types/rtcDataConfig.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rtcDataConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:rtc="http://www.wldelft.nl/fews" xmlns="http://www.wldelft.nl/fews" xsi:schemaLocation="http://www.wldelft.nl/fews C:\Werk\DHYDRO\Test_complexe_controllers\tests\dimrmodel_4types\rtc\rtcDataConfig.xsd">
  <importSeries>
    <PITimeSeriesFile>
      <timeSeriesFile>timeseries_import.xml</timeSeriesFile>
      <useBinFile>false</useBinFile>
    </PITimeSeriesFile>
    <timeSeries id="[Input]ObsS_98143/Water level (op)">
      <OpenMIExchangeItem>
        <elementId>ObsS_98143</elementId>
        <quantityId>Water level (op)</quantityId>
        <unit>m</unit>
      </OpenMIExchangeItem>
    </timeSeries>
    <timeSeries id="[Input]ObsS_96789/Water level (op)">
      <OpenMIExchangeItem>
        <elementId>ObsS_96789</elementId>
        <quantityId>Water level (op)</quantityId>
        <unit>m</unit>
      </OpenMIExchangeItem>
    </timeSeries>
    <timeSeries id="[SP]interval/Interval Rule">
      <PITimeSeries>
        <locationId>[IntervalRule]interval/Interval Rule</locationId>
        <parameterId>SP</parameterId>
        <interpolationOption>BLOCK</interpolationOption>
        <extrapolationOption>BLOCK</extrapolationOption>
      </PITimeSeries>
    </timeSeries>
    <timeSeries id="time/Time Rule">
      <PITimeSeries>
        <locationId>[TimeRule]time/Time Rule</locationId>
        <parameterId>TimeSeries</parameterId>
        <interpolationOption>LINEAR</interpolationOption>
        <extrapolationOption>BLOCK</extrapolationOption>
      </PITimeSeries>
    </timeSeries>
    <timeSeries id="reuseObsPoint/Time Rule">
      <PITimeSeries>
        <locationId>[TimeRule]reuseObsPoint/Time Rule</locationId>
        <parameterId>TimeSeries</parameterId>
        <interpolationOption>LINEAR</interpolationOption>
        <extrapolationOption>BLOCK</extrapolationOption>
      </PITimeSeries>
    </timeSeries>
  </importSeries>
  <exportSeries>
    <CSVTimeSeriesFile decimalSeparator="." delimiter="," adjointOutput="false"></CSVTimeSeriesFile>
    <PITimeSeriesFile>
      <timeSeriesFile>timeseries_export.xml</timeSeriesFile>
      <useBinFile>false</useBinFile>
    </PITimeSeriesFile>
    <timeSeries id="[Output]S_98143/Crest level (s)">
      <OpenMIExchangeItem>
        <elementId>S_98143</elementId>
        <quantityId>Crest level (s)</quantityId>
        <unit>m</unit>
      </OpenMIExchangeItem>
    </timeSeries>
    <timeSeries id="[IP]pid/PID Rule" />
    <timeSeries id="[DP]pid/PID Rule" />
    <timeSeries id="[Output]S_96789/Crest level (s)">
      <OpenMIExchangeItem>
        <elementId>S_96789</elementId>
        <quantityId>Crest level (s)</quantityId>
        <unit>m</unit>
      </OpenMIExchangeItem>
    </timeSeries>
    <timeSeries id="[Status]interval/Interval Rule" />
    <timeSeries id="[Output]S_96547/Crest level (s)">
      <OpenMIExchangeItem>
        <elementId>S_96547</elementId>
        <quantityId>Crest level (s)</quantityId>
        <unit>m</unit>
      </OpenMIExchangeItem>
    </timeSeries>
    <timeSeries id="[Output]S_96840/Crest level (s)">
      <OpenMIExchangeItem>
        <elementId>S_96840</elementId>
        <quantityId>Crest level (s)</quantityId>
        <unit>m</unit>
      </OpenMIExchangeItem>
    </timeSeries>
    <timeSeries id="[Status]reuseObsPoint/Standard Condition" />
  </exportSeries>
</rtcDataConfig>

=== Deltares/HYDROLIB/contrib/Arcadis/scripts/exampledata/Zwolle-Minimodel1D_runned/rtc/rtcDataConfig.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rtcDataConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:rtc="http://www.wldelft.nl/fews" xmlns="http://www.wldelft.nl/fews" xsi:schemaLocation="http://www.wldelft.nl/fews C:\Users\devop\Documents\Scripts\Hydrolib\HYDROLIB\contrib\Arcadis\scripts\exampledata\Zwolle-Minimodel1D\rtc\rtcDataConfig.xsd">
  <importSeries>
    <PITimeSeriesFile>
      <timeSeriesFile>timeseries_import.xml</timeSeriesFile>
      <useBinFile>false</useBinFile>
    </PITimeSeriesFile>
    <timeSeries id="[Input]measUpSW-S570/Water level (op)">
      <OpenMIExchangeItem>
        <elementId>measUpSW-S570</elementId>
        <quantityId>Water level (op)</quantityId>
        <unit>m</unit>
      </OpenMIExchangeItem>
    </timeSeries>
    <timeSeries id="[SP]Control group of SW-S570/CTR_SW-S570">
      <PITimeSeries>
        <locationId>[IntervalRule]Control group of SW-S570/CTR_SW-S570</locationId>
        <parameterId>SP</parameterId>
        <interpolationOption>BLOCK</interpolationOption>
        <extrapolationOption>BLOCK</extrapolationOption>
      </PITimeSeries>
    </timeSeries>
  </importSeries>
  <exportSeries>
    <CSVTimeSeriesFile decimalSeparator="." delimiter="," adjointOutput="false"></CSVTimeSeriesFile>
    <PITimeSeriesFile>
      <timeSeriesFile>timeseries_export.xml</timeSeriesFile>
      <useBinFile>false</useBinFile>
    </PITimeSeriesFile>
    <timeSeries id="[Output]SW-S570/Crest level (s)">
      <OpenMIExchangeItem>
        <elementId>SW-S570</elementId>
        <quantityId>Crest level (s)</quantityId>
        <unit>m</unit>
      </OpenMIExchangeItem>
    </timeSeries>
    <timeSeries id="[Status]Control group of SW-S570/CTR_SW-S570" />
  </exportSeries>
</rtcDataConfig>
